# k8s/base/app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: familyman-ui-service
spec:
  type: ClusterIP
  selector:
    app: familyman-ui
  ports:
    - name: nextjs
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: agent
      port: 8001
      targetPort: 8001
      protocol: TCP
