# k8s/base/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: familyman-ui-config
data:
  # Next.js configuration
  NODE_ENV: "production"
  PORT: "3000"

  # FastAPI agent configuration
  PYTHON_PORT: "8001"

  # Model configuration
  # USE_LITELLM: "false"
  # MODEL_NAME: "gemini-2.5-flash"
  USE_LITELLM: "true"
  MODEL_NAME: "openai/qwen3-coder-next:q4_K_M"
  OPENAI_API_BASE: "https://ollama.krishb.in/v1"
  OPENAI_API_KEY: "dummy"
  OPIK_URL_OVERRIDE: "https://opik.krishb.in/api"
  NOTES_DIR: /conversation_notes

  # Logging
  LOG_LEVEL: "info"
